"""add sys_custom_fields to job_status

Revision ID: da5bf64d9ae8
Revises: c76ba9174c93
Create Date: 2025-12-27 13:57:07.873482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da5bf64d9ae8'
down_revision: Union[str, Sequence[str], None] = 'c76ba9174c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospitals_creation_batch_id'), table_name='hospitals')
    op.add_column('job_status', sa.Column('sys_custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('job_status', 'processing_time_seconds',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_status', 'processing_time_seconds',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('job_status', 'sys_custom_fields')
    op.create_index(op.f('ix_hospitals_creation_batch_id'), 'hospitals', ['creation_batch_id'], unique=False)
    # ### end Alembic commands ###
